#Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

In [1]:
import numpy as np

In [4]:
list1=[1,3,4,5,6]
arr=np.array(list1)

In [5]:
type(arr)

numpy.ndarray

making n dimentional **array**

In [7]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [9]:
arr1.shape

(3, 5)

**doing with first array**

In [24]:
print(arr)#[1 3 4 5 6]
print(arr[:])#[1 3 4 5 6]
print(arr[1:])#[3 4 5 6]
print(arr[2:3])#[4]
print(arr[:3])#[1 3 4]
print(arr[:-1])#[1 3 4 5]
print(arr[:-2])#[1 3 4]

#reversing:
print(arr[::-1])#[6 5 4 3 1]
print(arr[::-2])#[6 4 1] jumping by 2 step from reverse

[1 3 4 5 6]
[1 3 4 5 6]
[3 4 5 6]
[4]
[1 3 4]
[1 3 4 5]
[1 3 4]
[6 5 4 3 1]
[6 4 1]


**Doing with n dimention Arrey**

In [29]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [25]:
#indexing
arr1[0][0]

np.int64(1)

In [30]:
arr1[1:] #column er jonn comma use korte hbe

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [27]:
arr1[1:][0]

array([2, 3, 4, 5, 6])

In [28]:
arr1[1:][0][0]

np.int64(2)

**do with row and column**

In [31]:
arr1[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [37]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [32]:
arr1[1:,2:4]

array([[4, 5],
       [5, 6]])

# EDA by numpy

In [38]:
arr

array([1, 3, 4, 5, 6])

In [40]:
arr<4

array([ True,  True, False, False, False])

In [41]:
arr[arr<4]

array([1, 3])

In [42]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [45]:
arr3=np.arange(1,20,2)#creating in shortcut

In [46]:
arr3.reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [51]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.random.randint(3,88,)#random generator

15

In [55]:
np.random.randint(3,88,5)#random generator 5 values

array([44, 37, 84, 51, 52])

In [56]:
np.random.randn(5,6) #random norma distribution

array([[-0.17677569, -0.98571295,  0.1639636 , -0.13456293, -0.143553  ,
        -1.38707338],
       [ 0.17744492, -0.56183704, -0.51299349,  0.38208252,  1.29425633,
        -0.39833833],
       [-0.40123085, -0.26445486,  0.01190552, -1.92698024,  0.61736783,
        -0.95200657],
       [-0.20835808, -0.34276524, -0.82922004, -0.54959208, -0.97271118,
        -0.15091863],
       [-0.99341594, -0.03383174,  0.46985844, -0.69855165, -2.0672446 ,
         0.40649096]])

In [57]:
np.random.random_sample((4,7)) # between o and 1

array([[0.01196578, 0.17174636, 0.76560158, 0.89031012, 0.90221897,
        0.07507647, 0.1471671 ],
       [0.77235469, 0.04972029, 0.62120688, 0.99119397, 0.85261399,
        0.35883967, 0.76375733],
       [0.04497314, 0.63850991, 0.33808284, 0.49489965, 0.03616077,
        0.55757189, 0.90048554],
       [0.84370505, 0.14115881, 0.04206867, 0.18200275, 0.11372815,
        0.17169305, 0.49910253]])

#Pandas Dataframe


In [3]:
import pandas as pd
import numpy as np

In [5]:
arr1=np.arange(0,20).reshape(5,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
pd.DataFrame(arr1)

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [9]:
df=pd.DataFrame(arr1,index=["Row1", "Row2","Row3","Row4","Row5"],
             columns=["Column1", "Column2", "Column3", "Column4"])
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [12]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

**Indexing**
columnname,rowindex[loc],rowindex columnindex number[.iloc]

 Indexing  by column

In [17]:
#indexing by column
p=df['Column1']

In [19]:
type(p) #series

pandas.core.series.Series

In [20]:
q=df[['Column1','Column2','Column3']]#if more than one column the it should be in nested list

In [21]:
type(q) #DataFrame

pandas.core.frame.DataFrame

**indexing by row**

In [23]:
df.loc['Row2']

Column1    4
Column2    5
Column3    6
Column4    7
Name: Row2, dtype: int64

In [24]:
df.loc[['Row2','Row3']]

Column1  Column2  Column3  Column4
Row2        4        5        6        7
Row3        8        9       10       11

**Row + Colummn index**

In [26]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [25]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

Converting df to array

In [27]:
#.vslues dilei hoye jabe
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [28]:
df.iloc[1:3,1:3].values

array([[ 5,  6],
       [ 9, 10]])

**Checking the null value**

In [43]:
df=pd.DataFrame(data=[[1,np.nan,2,3],[3,3,4,5],[7,9,4,5]],index=["Row1",
                                                      "Row2","Row3"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                              "Column4"
                                                                             ])

In [44]:
df

Column1  Column2  Column3  Column4
Row1        1      NaN        2        3
Row2        3      3.0        4        5
Row3        7      9.0        4        5

In [45]:
df.isnull()

Column1  Column2  Column3  Column4
Row1    False     True    False    False
Row2    False    False    False    False
Row3    False    False    False    False

In [46]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
Column4    0
dtype: int64

In [55]:

print(df['Column2'].value_counts())
print(df['Column1'].value_counts())
print("the column2 contains {}".format( df['Column1'].unique()))

Column2
3.0    1
9.0    1
Name: count, dtype: int64
Column1
1    1
3    1
7    1
Name: count, dtype: int64
the column2 contains [1 3 7]


In [64]:
df['Column2'].values

array([nan,  3.,  9.])

Canditional dataframe

In [73]:
df[df['Column2']>5]

Column1  Column2  Column3  Column4
Row3        7      9.0        4        5

# Pandas series

**`how to create csv file `**

In [74]:
import pandas as pd
from io import StringIO

In [112]:
data=('col1,col2,col3,col4\n x,y,z,1\n a,b,c,2\n x,y,z,')#auto row index kore nibe
type(data)

str

In [113]:
csv1=StringIO(data)
csv1

In [115]:
df1=pd.read_csv(StringIO(data))
df1

col1 col2 col3  col4
0    x    y    z   1.0
1    a    b    c   2.0
2    x    y    z   NaN

In [116]:
df1['col1'][1]

' a'

In [117]:
df.dtypes

col1    object
col2    object
col3    object
col4     int64
dtype: object

In [120]:
df=pd.read_csv(StringIO(data),dtype='object')
df.dtypes

col1    object
col2    object
col3    object
col4    object
dtype: object

In [121]:
##datatypes in csv
data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')

In [122]:
df=pd.read_csv(StringIO(data),dtype={'a':int,'b':float,'c':int})

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int64  
 1   b       3 non-null      float64
 2   c       3 non-null      int64  
 3   d       2 non-null      float64
dtypes: float64(2), int64(2)
memory usage: 228.0 bytes


In [124]:
data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')

In [127]:
pd.read_csv(StringIO(data)) #we want to make the previous index column in new data set

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [128]:
pd.read_csv(StringIO(data),index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [130]:
pd.read_csv(StringIO(data),index_col=0,usecols=['index','b','c'])

b     c
index           
4      bat   5.7
8      cow  10.0

In [134]:
#tab seperated dataset
from os import link
link="https://download.bls.gov/pub/time.series/cu/cu.item"
df=pd.read_csv(link,sep='\t')

HTTPError: HTTP Error 403: Forbidden